#!/usr/bin/env ruby

require 'rubygems'
require 'irb'

begin
  ap_dir = File.join(File.dirname(__FILE__), "../lib")
  raise LoadError unless File.exists?(ap_dir) && File.exists?(File.join(ap_dir, 'palmade/asset_packager.rb'))
  
  puts "Using local asset_packager package"
  $:.unshift(ap_dir)
  require 'palmade/asset_packager'
rescue LoadError
  version = "> 0"
  if ARGV.first =~ /^_(.*)_$/ and Gem::Version.correct? $1 then
    version = $1
    ARGV.shift
  end
  gem 'asset_packager', version
  require 'palmade/asset_packager'
end

STDERR.puts "Hello World!"
IRB.start
